#!/bin/bash

# Download training data
echo "Downloading training data..."
mkdir -p Data
python scripts/Download_data.py 1-0oEO1ZikKR_JYAakYb2ejfWVXd9CTlI Data/action_index.json
python scripts/Download_data.py 1Fg_3n6lcImQc6WhJ69XHzZmfTt9-PZL_ Data/prior_mask_1.pkl
python scripts/Download_data.py 1dtFAbgRkaPB8C3bkiyZep9s43jpMIcUL Data/fastText_new.pkl
python scripts/Download_data.py 1DxLijkO9JvYRDFnU4ezA19wsUURfD8Qj Data/hico_list_hoi.txt
python scripts/Download_data.py 1eSqmCzwi1JVxy01WM0Ye8saHGu04Ox2C Data/hico_list_vb.txt
python scripts/Download_data.py 1-PzF3ldZGwwVgseCyOip4rxwAdsKOZIe Data/Test_Faster_RCNN_R-50-PFN_2x_HICO_DET.pkl
python scripts/Download_data.py 1JjlmjPAsctz9EeoTmx6PSRNQvuViNtAl Data/Test_Faster_RCNN_R-50-PFN_2x_VCOCO.pkl
python scripts/Download_data.py 18_6K2P6s9vMBWOvcNNQqUj2wfLhbvpLo Data/test_HICO_finetuned_v3.pkl
python scripts/Download_data.py 1-oZzkedShP9lNrZmYfpNh7LPNKMqdqNK Data/threshold.pkl
python scripts/Download_data.py 1SN7AeWHoGbxq-fakrWJg0YI7ZY2KmwNM Data/Train_Graph_GT_Hcentric_HICO_dict.pkl
python scripts/Download_data.py 1BZQwI-S_DU3KQULLY1CiOrEprmwQo38z Data/Train_Graph_GT_Ocentric_HICO_dict.pkl
python scripts/Download_data.py 1YYuj88xX8B9X_y_YQeVlBShbsthAeUjj Data/Val_Graph_GT_Hcentric_HICO_dict.pkl
python scripts/Download_data.py 1ZcJj_IQLnnoud5d4zwJRTzXSOguNLKSi Data/Val_Graph_GT_Ocentric_HICO_dict.pkl
python scripts/Download_data.py 1laiQnNNzFLVn2JaERI1qH8TNt8S2J7Eu Data/Train_Graph_GT_Hcentric_VCOCO_dict.pkl
python scripts/Download_data.py 1XF4_UJpOxd2M87Dg23-dD6JMHdId3_Al Data/Train_Graph_GT_Ocentric_VCOCO_dict.pkl
python scripts/Download_data.py 1xzJho4WHV3Kycgl7RyNrnBsOztgVPZ7y Data/Val_Graph_GT_Hcentric_VCOCO_dict.pkl
python scripts/Download_data.py 1Kvoho8JRkoNPqdGSJ_Jbrynr1aJoBwO8 Data/Val_Graph_GT_Ocentric_VCOCO_dict.pkl
python scripts/Download_data.py 1H7IdMSFOQ4nksUl0AaCz4EDqj_ai1Xt7 Data/Trainval_Neg_HICO_dict.pkl
python scripts/Download_data.py 162WYWpJgxhALt2xYfO9ncisgIW0H2Pmj Data/Trainval_Neg_VCOCO_dict.pkl
python scripts/Download_data.py 1LLIMyNNMwMOSLBAzuLzUxEUVcqxf7v7n Data/hico_hoi_list.pkl
python scripts/Download_data.py 1RpeUAecgsS88KT61b384D2SlQNz5RWmL Data/hico_bin_to_hoi_ids.pkl
python scripts/Download_data.py 1NfwdGecqREmhHjYMCWGCHMOlbLvq2Wy8 Data/hico_hoi_map_to_obj_vb.pkl
python scripts/Download_data.py 1YHmrIxiK2xIkVw8u8E9LpMT76iFW4eon Data/hico_split_ids.pkl
python scripts/Download_data.py 1kjy6gI7EKgJBrQGZ87tN_w-2K9u62pyT Data/hico_anno_traintest_list.pkl
